In [14]:
import netlist_gen
import numpy as np
from scipy.optimize import minimize
import scipy as sp

In [24]:
N = 100
mask = np.random.choice(a=[True, False], size=(N,N), p=[0.5, 0.5])
mask = np.logical_and(mask, mask.T)
res = np.random.random(size=(N,N))
res = (res + res.T) 

In [25]:
(res == res.T).all()

True

In [15]:
def min_fun(mat):
    def pwr_dis(x):
        pwr = 0
        for i in range(len(x)):
            for j in range(len(x)):
                pwr += int(x[i]>x[j])*(x[i]-x[j])**2*mat[i,j]

        return pwr
    return pwr_dis

def better_obj(mat):
    def pwr_dis(x):
        xs = np.repeat(x[:,None], x.shape, 1)
        return np.sum((xs > xs.T).astype(int)*(xs - xs.T)**2*mat)
    return pwr_dis

In [26]:
mat = res
obj = min_fun(mat)
obj_opt = better_obj(mat)

In [23]:
x0 = np.random.random(N)
v0 = 5
bounds = [(None, None) for _ in range(N)]
bounds[0] = (v0, v0)
bounds[-1] = (0, 0)

In [27]:
res_opt = minimize(obj_opt, x0, bounds=bounds)

In [28]:
res = minimize(obj, x0, bounds=bounds)

In [32]:
res.x

array([5.        , 2.60171218, 2.57311927, 2.61293521, 2.60128942,
       2.58464114, 2.56657739, 2.56979699, 2.5780432 , 2.58913193,
       2.59180189, 2.5821804 , 2.60033878, 2.61270639, 2.57876328,
       2.58303061, 2.56440313, 2.5848872 , 2.59412572, 2.5928276 ,
       2.57249085, 2.60167126, 2.57539609, 2.58027113, 2.58106088,
       2.58203187, 2.578017  , 2.62554084, 2.58697528, 2.55797322,
       2.59255682, 2.61779678, 2.58901616, 2.59649785, 2.56491538,
       2.59457052, 2.591314  , 2.56025741, 2.58189999, 2.58808624,
       2.59559069, 2.59157147, 2.60036359, 2.58876033, 2.59410981,
       2.59254482, 2.60614984, 2.60471829, 2.6175524 , 2.57500387,
       2.58242909, 2.59234969, 2.58367934, 2.5864859 , 2.6060638 ,
       2.59790122, 2.59197595, 2.59080398, 2.57554936, 2.59953741,
       2.60199615, 2.6221917 , 2.59252084, 2.58093864, 2.6016611 ,
       2.59797111, 2.5754555 , 2.57442017, 2.61496945, 2.57791808,
       2.57728061, 2.59632195, 2.58935038, 2.58175844, 2.57720

In [34]:
res_opt.x - res.x

array([ 0.00000000e+00, -1.08869786e-06, -8.00768932e-07, -7.24638836e-07,
       -9.47917179e-07, -9.05281778e-07, -6.33469247e-07, -7.10782238e-07,
       -9.97473404e-07, -1.05889467e-06, -7.91142261e-07, -8.87450077e-07,
       -1.12316860e-06, -9.27704827e-07, -7.78398883e-07, -7.29620969e-07,
       -8.81955494e-07, -8.82182522e-07, -6.55280525e-07, -1.09553468e-06,
       -7.31598836e-07, -8.77478612e-07, -1.13467811e-06, -1.04584350e-06,
       -6.63051803e-07, -6.68767613e-07, -9.50650561e-07, -8.08209922e-07,
       -7.91696003e-07, -5.41170020e-07, -5.86385101e-07, -8.88934420e-07,
       -6.85002561e-07, -1.00372958e-06, -1.30038640e-06, -9.23662125e-07,
       -1.03210221e-06, -4.82649626e-07, -1.11256033e-06, -1.09741565e-06,
       -5.81127030e-07, -1.06396282e-06, -5.72216079e-07, -6.20588350e-07,
       -8.91876734e-07, -9.87490408e-07, -9.80513252e-07, -1.16893187e-06,
       -5.98201066e-07, -4.49838137e-07, -3.82306090e-07, -8.78187274e-07,
       -1.22396595e-06, -

In [20]:
res.x

array([0.5157375 , 0.51573754, 0.51573745, 0.51573743, 0.51573751,
       0.51573749, 0.51573743, 0.51573742, 0.51573749, 0.51573748,
       0.51573748, 0.51573745, 0.51573746, 0.51573748, 0.51573747,
       0.51573742, 0.51573746, 0.51573743, 0.51573744, 0.51573741,
       0.51573746, 0.51573739, 0.51573744, 0.51573741, 0.51573745,
       0.5157374 , 0.51573748, 0.51573742, 0.51573748, 0.51573742,
       0.5157375 , 0.51573744, 0.51573746, 0.51573736, 0.51573747,
       0.5157374 , 0.51573751, 0.51573745, 0.51573747, 0.51573746,
       0.51573733, 0.51573747, 0.51573744, 0.51573742, 0.5157374 ,
       0.51573753, 0.51573746, 0.51573743, 0.51573749, 0.5157375 ,
       0.51573743, 0.51573744, 0.51573745, 0.51573747, 0.51573743,
       0.51573749, 0.51573743, 0.51573742, 0.51573748, 0.51573751,
       0.51573745, 0.51573738, 0.51573747, 0.51573743, 0.51573743,
       0.51573745, 0.5157374 , 0.51573745, 0.51573759, 0.51573739,
       0.51573753, 0.5157374 , 0.51573746, 0.51573748, 0.51573

In [4]:
netlist_gen.gen_netlist(mat, "test.cir")