In [240]:
%load_ext autoreload
%autoreload 2
from opt import * 
import numpy as np

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


#### Initialize randomized resistor matrix

In [241]:
mat = np.random.rand(3, 3)
mat += mat.T
mat[0, -1] = 0
mat[-1, 0] = 0

In [242]:
xs = np.array([5])[:, None]
ys = np.array([2.5])[:, None]
node_cfg = np.array([1, -1, 0])

In [243]:
mat

array([[1.08487539, 0.91673323, 0.        ],
       [0.91673323, 1.44133169, 0.46177999],
       [0.        , 0.46177999, 1.5351776 ]])

In [244]:
gamma = 0.1
epochs = 30

In [249]:
trained = train(mat, xs, ys, node_cfg, epochs=epochs, gamma=gamma)

[[5 None]
 [None None]
 [0 0]]
[[5 None]
 [2.5023776699435523 2.5023776699435523]
 [0 0]]
[5.         2.50264186 0.        ] [5.         2.50237767 0.        ]
[[ 0.          0.00013196  0.        ]
 [ 0.00013196  0.         -0.00013223]
 [ 0.         -0.00013223  0.        ]]
[[5 None]
 [None 2.5023776699435523]
 [0 0]]
[[5 None]
 [2.5019693586568326 2.5019693586568326]
 [0 0]]
[5.         2.50218818 0.        ] [5.         2.50196936 0.        ]
[[ 0.          0.00010932  0.        ]
 [ 0.00010932  0.         -0.0001095 ]
 [ 0.         -0.0001095   0.        ]]
[[5 None]
 [None 2.5019693586568326]
 [0 0]]
[[5 None]
 [2.501630838370266 2.501630838370266]
 [0 0]]
[5.         2.50181204 0.        ] [5.         2.50163084 0.        ]
[[ 0.00000000e+00  9.05397452e-05  0.00000000e+00]
 [ 9.05397452e-05  0.00000000e+00 -9.06645182e-05]
 [ 0.00000000e+00 -9.06645182e-05  0.00000000e+00]]
[[5 None]
 [None 2.501630838370266]
 [0 0]]
[[5 None]
 [2.501350571111303 2.501350571111303]
 [0 0]]
[5.

In [246]:
mat, trained

(array([[1.08487539, 0.72830574, 0.        ],
        [0.72830574, 1.44133169, 0.72676811],
        [0.        , 0.72676811, 1.5351776 ]]),
 array([[1.08487539, 0.72830574, 0.        ],
        [0.72830574, 1.44133169, 0.72676811],
        [0.        , 0.72676811, 1.5351776 ]]))

In [247]:
bounds = np.array([[5, None], [None, None], [0,0]])

In [248]:
solve(mat, bounds).x, solve(trained, bounds).x

(array([5.        , 2.50264188, 0.        ]),
 array([5.        , 2.50264191, 0.        ]))