In [95]:
%load_ext autoreload
%autoreload 2
from scipy.optimize import minimize
from scipy.optimize import approx_fprime
from opt import *
import numpy as np

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


### Linear (resistor only) simulation

In [96]:
approx_fprime(np.zeros(4), better_obj(res_mat))

array([7.45058060e-07, 1.50501728e-06, 7.45058060e-07, 1.49011612e-06])

In [97]:
R = 50
X = 1 # value of X is a placeholder -- doesn't matter
v0 = 5

res_mat = np.array([[X, R, 0, 0], 
                    [R, X, 1, R], 
                    [0, 0, X, R], 
                    [0, R, R, X]])


In [98]:
n = 50

rand_mat = np.random.rand(n, n)

N = 100
mask = np.random.choice(a=[True, False], size=(N,N), p=[0.5, 0.5])
mask = np.logical_and(mask, mask.T)
res = np.random.random(size=(N,N))
res = (res + res.T) * mask

big_mat = res

x0_big = np.random.rand(n)
obj_big = min_fun(big_mat)

bounds = [(None, None) for _ in range(n)]
bounds[0] = (v0, v0)
bounds[-1] = (0, 0)

In [99]:
res_big = minimize(obj_big, x0_big, bounds=bounds)

In [100]:
res_big

      fun: 125.27419831462294
 hess_inv: None
      jac: array([            nan,  0.00000000e+00,  9.37916417e-05, -9.94759836e-06,
       -2.70006241e-05, -7.53175304e-05,  1.00897069e-04, -1.20792266e-04,
       -2.84217096e-05, -8.81072998e-05, -6.11066756e-05, -4.54747354e-05,
        2.85638182e-04,  7.81597014e-05, -9.94759836e-06,  4.12114789e-05,
       -8.66862143e-05, -2.98427951e-05,  8.38440433e-05,  6.67910176e-05,
        1.13686838e-04, -1.00897069e-04, -1.09423582e-04, -1.00897069e-04,
        0.00000000e+00,  1.27897693e-05, -5.40012482e-05,  1.02318155e-04,
        8.95283852e-05, -1.35003121e-04, -9.09494707e-05, -1.05160326e-04,
       -9.37916417e-05, -1.27897693e-05,  2.81374925e-04,  1.42108548e-05,
        3.31112917e-04,  1.70530258e-04, -8.52651288e-06,  6.53699321e-05,
       -3.55271370e-05,  6.82121030e-05, -3.28270746e-04,  6.39488466e-05,
        3.26849660e-05, -9.23705562e-05, -2.84217096e-05,  1.42108548e-06,
       -1.54898317e-04,             nan])
 

In [101]:
big_mat

array([[1.10747509, 0.        , 0.        , ..., 0.        , 0.        ,
        0.54565803],
       [0.        , 1.36353834, 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.37061191, ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.54565803, 0.        , 0.        , ..., 0.        , 0.        ,
        0.21968306]])

In [102]:
np.min(big_mat), np.max(big_mat)

(0.0, 1.9845850722831448)

In [103]:
res_big.x

array([5.        , 2.32900495, 2.42130791, 2.38564904, 2.39533003,
       2.35371387, 2.351004  , 2.42219965, 2.4976438 , 2.54282051,
       2.37086341, 2.3992591 , 2.52650106, 2.34687557, 2.41517992,
       2.41383409, 2.29150282, 2.28670155, 2.33861674, 2.45665269,
       2.23471591, 2.34268733, 2.36904176, 2.70897921, 2.21473123,
       2.40500868, 2.46286123, 2.45733358, 2.29331239, 2.04967216,
       2.29431435, 2.18068432, 2.45104032, 2.40807067, 2.36957768,
       2.16027514, 2.73056464, 2.37270132, 2.46519404, 2.37604834,
       2.20118612, 1.97756714, 2.4789568 , 2.3727729 , 2.358936  ,
       2.36542196, 2.23424571, 2.70328629, 2.10701864, 0.        ])

In [104]:
x0 = np.zeros(4)
obj = min_fun(res_mat)

res = minimize(obj, x0, bounds=((v0, v0), (None, None), (None, None), (0,0)))

In [105]:
obj_opt = better_obj(res_mat)
res_opt = minimize(obj_opt, x0, bounds=((v0, v0), (None, None), (None, None), (0,0)))

In [106]:
res

      fun: 631.0679611650492
 hess_inv: None
      jac: array([nan,  0.,  0., nan])
  message: 'CONVERGENCE: NORM_OF_PROJECTED_GRADIENT_<=_PGTOL'
     nfev: 15
      nit: 4
     njev: 5
   status: 0
  success: True
        x: array([5.        , 2.47572822, 0.04854363, 0.        ])

In [107]:
res_opt

      fun: 631.0679611650492
 hess_inv: None
      jac: array([nan,  0.,  0., nan])
  message: 'CONVERGENCE: NORM_OF_PROJECTED_GRADIENT_<=_PGTOL'
     nfev: 15
      nit: 4
     njev: 5
   status: 0
  success: True
        x: array([5.        , 2.47572822, 0.04854363, 0.        ])

In [108]:
res.x

array([5.        , 2.47572822, 0.04854363, 0.        ])

### Simulation with ReLu element

In [109]:
R = 1/100
X = 0
v0 = 5

# diode facing forward
forward_mat = np.array([[X, R, 0, 0], 
                        [R, X, 1, R], 
                        [0, 0, X, R], 
                        [0, R, R, X]])

# diode facing backward
backward_mat = np.array([[X, R, 0, 0], 
                        [R, X, 0, R], 
                        [0, 1, X, R], 
                        [0, R, R, X]])

In [110]:
x0_fwd = np.random.rand(4)
obj_fwd = min_fun(forward_mat)

res_fwd = minimize(obj_fwd, x0_fwd, bounds=((v0, v0), (None, None), (None, None), (0,0)))

x0_rev = np.random.rand(4)
obj_rev = min_fun(backward_mat)

res_rev = minimize(obj_rev, x0_rev, bounds=((v0, v0), (None, None), (None, None), (0,0)))

In [111]:
res_fwd.x

array([5.        , 1.67218348, 1.65562715, 0.        ])

In [112]:
res_fwd

      fun: 0.16639072847693803
 hess_inv: None
      jac: array([            nan,  8.32667274e-09, -1.02695630e-07,             nan])
  message: 'CONVERGENCE: NORM_OF_PROJECTED_GRADIENT_<=_PGTOL'
     nfev: 36
      nit: 6
     njev: 12
   status: 0
  success: True
        x: array([5.        , 1.67218348, 1.65562715, 0.        ])

In [113]:
res_rev.x

array([ 5.00000000e+00,  2.49999995e+00, -1.30423014e-07,  0.00000000e+00])

### Simple line example -- linear vs. nonlinear

In [114]:
R = 100
X = 1 # value of X is a placeholder -- doesn't matter
v0 = 5

lne_mat = np.array([[X, R, np.inf, np.inf], 
                    [R, X, R, np.inf], 
                    [np.inf, R, X, R], 
                    [np.inf, np.inf, R, X]])


In [115]:
x0 = np.zeros(4)
obj_lne = min_fun(res_mat)

res_lne = minimize(obj_lne, x0, bounds=((v0, v0), (None, None), (None, None), (0,0)))

In [116]:
res_lne.x

array([5.        , 2.47572822, 0.04854363, 0.        ])